cat <<——— > index.html
  <!doctype html>

  <! -- THIS IS AN AUTOGENERATED FILE!!! MODIFICATIONS WILL BE OVERWRITETN -->
  <! -- PLEASE UPDATE live.sh instead -->

  <head>
  <link rel="stylesheet" href="style.css" />
  <script src="elm.js"></script>
  <script src="vendor/viz/viz.js"></script>
  <script src="vendor/viz/full.render.js"></script

  </head>
  <body>
    <div id="svg-container"></div>
    <div id="paper-svg-container"></div>
    <div id="elm"></div>

    <script>
      var viz = new Viz();
      var vizPaperOutline = new Viz();
    </script>

    <script>
      var app = Elm.Main.init({ node: document.getElementById("elm") })
      var svgContainer = document.getElementById("svg-container");
      var paperSvgContainer = document.getElementById("paper-svg-container");



      app.ports.repaintGraph.subscribe(function (dotOutput) {
        viz.renderSVGElement(dotOutput)
        .then(function(element) {
          svgContainer.innerHTML = "";
          svgContainer.appendChild(element);
        })
        .catch(error => {
          // Create a new Viz instance (@see Caveats page for more info)
          viz = new Viz();

          // Possibly display the error
          console.error(error);
        });
      })


      app.ports.renderPaperOutline.subscribe(function (dotOutput) {
        vizPaperOutline.renderSVGElement(dotOutput)
        .then(function(element) {
          paperSvgContainer.innerHTML = "";
          paperSvgContainer.appendChild(element);
        })
        .catch(error => {
          // Create a new Viz instance (@see Caveats page for more info)
          vizPaperOutline = new Viz();

          // Possibly display the error
          console.error(error);
        });
      })
    </script>


  </body>
———

elm-live src/Main.elm --output=elm.js --open
